name: Semgrep Check

on:
  push:
    branches:
      - master
    paths:
      - '**.py'
  pull_request:
    branches:
      - master
    paths:
      - '**.py'

jobs:
  semgrep-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install Semgrep
        run: |
          pip install semgrep

      - name: Run Semgrep
        run: |
          semgrep --config=semgrep/semgrep_rules.yaml .
        continue-on-error: true
      - name: Verify Semgrep setup
        run: |
          semgrep --version
          semgrep --list

      - name: Check Semgrep results
        run: |
          echo "Semgrep found issues:"
          echo "steps": "${{ steps}}"
          echo "semgrep": "${{ steps.semgrep }}"
          echo "Outcome: ${{ steps.semgrep.outcome }}"
          if [ "${{ steps.semgrep.outcome }}" == "failure" ]; then
            echo "Semgrep found issues:"
            echo "${{ steps.semgrep.outputs.results }}"
            exit 1
          else
            echo "No issues found by Semgrep."
          fi
