name: Semgrep Check

on:
  push:
    branches:
      - master
    paths:
      - '**.py'
  pull_request:
    branches:
      - master
    paths:
      - '**.py'

jobs:
  semgrep-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install Semgrep
        run: |
          pip install semgrep

      - name: Run Semgrep
        run: |
          semgrep --config=semgrep/semgrep_rules.yaml --config=semgrep/code_quality.yaml . --error 

      - name: Check Semgrep Results
        run: |
          echo "${{ steps.semgrep.outputs}}
