name: Python Unit Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Run Python Unit Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'  # Specify your Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Replace with your requirements file if needed

    - name: Identify modified Python test files
      id: find_files
      run: |
        echo "::set-output name=modified_test_files::$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '.py')"
        
    - name: Install Frappe framework
      run: |
        pip install frappe
    

    - name: Run unit tests for modified files
      run: |
        modified_files="${{ steps.find_files.outputs.modified_files }}"
        while IFS= read -r file; do
          test_file=$(echo "$file" | sed 's|/|/test_|' | sed 's|\.py$|.py|')
          if [ -f "$test_file" ]; then
            python -m unittest $test_file
          fi
        done <<< "$modified_files"
