name: Python Unit Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Run Python Unit Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'  # Specify your Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Replace with your requirements file if needed

    - name: Identify modified Python test files
      id: find_files
      run: |
        echo "::set-output name=modified_test_files::$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -E 'test.*\.py')"
        
    - name: Install Frappe framework
      run: |
        pip install frappe
    

    - name: Run unit tests for modified test files
      run: |
        echo "steps: ${{ steps }}"
        echo "findfiles: ${{ steps.find_files }}"
        echo "output: ${{ steps.find_files.outputs}}"
        if [ -n "${{ steps.find_files.outputs.modified_test_files }}" ]; then
          python -m unittest discover -s $(dirname "${{ steps.find_files.outputs.modified_test_files }}") -p 'test*.py'
        else
          echo "No modified test files found, skipping tests."
        fi
